# Generated by Django 5.1 on 2024-08-30 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2)),
                ('branch_code', models.CharField(max_length=4, unique=True)),
                ('branch_name', models.CharField(choices=[('AI/DS', 'Artificial Intelligence/Data Science'), ('IT', 'Information Technology'), ('Comps', 'Computer Science'), ('ACT', 'Actuarial Science'), ('VLSI', 'VLSI Design')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Subject', max_length=100)),
                ('code', models.CharField(default='Unknown Code', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryPractical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSelection',
            fields=[
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.branchcode')),
                ('component_1', models.CharField(default='Power Point Presentation', max_length=50)),
                ('component_2', models.CharField(default='Group Discussion', max_length=50)),
                ('component_3', models.CharField(default='Seminar presentation', max_length=50)),
                ('component_4', models.CharField(default='Quiz', max_length=50)),
                ('component_5', models.CharField(default='Case study', max_length=50)),
                ('component_6', models.CharField(default='Design thinking', max_length=50)),
                ('component_7', models.CharField(default='Innovation', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('prn', models.CharField(default='Unknown PRN', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Student', max_length=100)),
                ('registration_number', models.CharField(default='N/A', max_length=20)),
                ('roll_number', models.CharField(default='N/A', max_length=20)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.branchcode')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_sem_marks', models.FloatField(default=0.0)),
                ('cce_marks', models.FloatField(default=0.0)),
                ('end_sem_marks', models.FloatField(default=0.0)),
                ('practical_write_up', models.FloatField(default=0.0)),
                ('attendance', models.FloatField(default=0.0)),
                ('end_sem_practical', models.FloatField(default=0.0)),
                ('ppt_content', models.IntegerField(default=0)),
                ('ppt_organization', models.IntegerField(default=0)),
                ('ppt_design', models.IntegerField(default=0)),
                ('ppt_delivery', models.IntegerField(default=0)),
                ('ppt_audience_engagement', models.IntegerField(default=0)),
                ('ppt_qna', models.IntegerField(default=0)),
                ('group_discussion_content_knowledge', models.IntegerField(default=0)),
                ('group_discussion_communication_skills', models.IntegerField(default=0)),
                ('group_discussion_participation', models.IntegerField(default=0)),
                ('group_discussion_team_work', models.IntegerField(default=0)),
                ('seminar_content', models.IntegerField(default=0)),
                ('seminar_organization', models.IntegerField(default=0)),
                ('seminar_presentation_skills', models.IntegerField(default=0)),
                ('seminar_visual_aids', models.IntegerField(default=0)),
                ('seminar_response_to_questions', models.IntegerField(default=0)),
                ('quiz_mcqs', models.IntegerField(default=0)),
                ('quiz_short_answer_questions', models.IntegerField(default=0)),
                ('case_study_understanding', models.IntegerField(default=0)),
                ('case_study_analysis_and_application', models.IntegerField(default=0)),
                ('case_study_solution', models.IntegerField(default=0)),
                ('case_study_organization', models.IntegerField(default=0)),
                ('case_study_clarity', models.IntegerField(default=0)),
                ('case_study_references', models.IntegerField(default=0)),
                ('design_thinking_problem_definition', models.IntegerField(default=0)),
                ('design_thinking_ideation', models.IntegerField(default=0)),
                ('design_thinking_prototyping', models.IntegerField(default=0)),
                ('design_thinking_testing', models.IntegerField(default=0)),
                ('design_thinking_reflection', models.IntegerField(default=0)),
                ('innovation_originality', models.IntegerField(default=0)),
                ('innovation_impact', models.IntegerField(default=0)),
                ('innovation_feasibility', models.IntegerField(default=0)),
                ('innovation_implementation_strategy', models.IntegerField(default=0)),
                ('innovation_creativity', models.IntegerField(default=0)),
                ('mse_marks', models.FloatField(default=0.0)),
                ('ese_marks', models.FloatField(default=0.0)),
                ('total_marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('theory_or_practical', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.theorypractical')),
            ],
        ),
    ]
